version: "3.1"
services:
    app:
        image: app:1.0
        container_name: appcontainer
        build:
            context: ./
        restart: always
        ports:
          - "81:80"
        volumes:
          - ../app:/var/www/html